### ISSUE TITLE
Please "git tag" your RAKU modules with it's versions

### ISSUE THREAD

**Issue by AntonOks** [krunen/term-termios#15]
Can you please set a specific "version" for your RAKU module in your META6.json file? You have a '*" now, which is known to make trouble and may not be supported within the RAKU tool chain (soon), say ZEF, FEZ, MI6...

And can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's **_"version": "x.y.z"_** in your `META6.json` file, then and in the future?

I was told, this will happen "for free" going forward with mi6 anyhow, but for now it would be great if you spend those 2 seconds already now :)

"Tagging" is generally highly appreciated in regards to "reproducible builds" and here especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by AntonOks** [comment]
@krunen @titsuki ping...

**Comment by titsuki** [comment]
@AntonOks 
Hi,
Thanks for your comment. 
But I'm not a maintainer of this repository and I don't have permission for tagging version. 

I think he doesn't notice your ping since he isn't active on github over a couple of years.
How about you try sending an email to him?

**Comment by krunen** [comment]
Hi,
I'll look into it. I have to set up a few things, but it's time to get into Raku again!

**Comment by krunen** [comment]
Done. I tested installing with zef with 23.06, no errors.

**Comment by AntonOks** [comment]
> Done. I tested installing with zef with 23.06, no errors.

Hi. please read the opened "issue".. aka wish / request.
This is not about "it's not installing via ZEF"... it's about having a clear development status of software in general... and to have a basis / way for [reproducible builds](https://reproducible-builds.org/) of software.
