### ISSUE TITLE
Please "git tag" your RAKU modules with it's versions

### ISSUE THREAD

**Issue by AntonOks** [krunen/term-termios#16]
As you closed #15 , this is a way of re-opening it again.

-----

Can you please set a specific "version" for your RAKU module in your META6.json file? You have a '*" now, which is known to make trouble and may not be supported within the RAKU tool chain (soon), say ZEF, FEZ, MI6...

And can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's "version": "x.y.z" in your META6.json file, then and in the future?

I was told, this will happen "for free" going forward with mi6 anyhow, but for now it would be great if you spend those 2 seconds already now :)

"Tagging" is generally highly appreciated in regards to "reproducible builds" and here especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by krunen** [comment]
Sorry, did you misunderstand me? My "Done" meant that I have changed the version in META6.json, and tagged with the same version, just as you requested.

**Comment by AntonOks** [comment]
> Sorry, did you misunderstand me? My "Done" meant that I have changed the version in META6.json, and tagged with the same version, just as you requested.

Hmm, there are no "git tags" here, see https://github.com/krunen/term-termios/tags
If you "git tag"'ed a local repository, you may want to re-push the tags?!? i.e. with `git push <origin> --tags`, see https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by krunen** [comment]
Sorry, I forgot that, done now.

**Comment by AntonOks** [comment]
THANK YOU!!!!
