### ISSUE TITLE
Consider migrating to "zef ecosystem"

### ISSUE THREAD

**Issue by 2colours** [krunen/term-termios#18]
Hello,

good to see you back. This dist continues to back up many of the most essential TUI distributions in the Raku world.

In the meantime, the old p6c ecosystem has been declining due to its obvious limitations - lack of versioning and author integrity. Please consider to [release this module to the "zef ecosystem", using the fez tool](https://docs.raku.org/language/modules#Upload_your_module_to_zef_ecosystem). 

Thanks in advance.

**Comment by krunen** [comment]
I have done so now. I struggled a bit with the META.json file, but version 0.2.3 seems to work fine.
