### ISSUE TITLE
resources was removed from meta file

### ISSUE THREAD

**Issue by hythm7** [krunen/term-termios#19]
Looks like [this](https://github.com/krunen/term-termios/commit/5df92d844d9c481fd9758175106da55246cda419#diff-ed5c10babba5a16dd251cedebb96631a8e1e9d3644712e7df37a75e98c5e41b5L9) commit removed `libraries/myhelper` from resources, which has broken the module.

To reproduce the issue,  I install `Terminal::LineEditor` which depends on `Term::termios`, then run `raku`, the repl doesn't load and continuously throws error
relevant part in the error is:
```sh
Use of uninitialized value element of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in sub guess_library_name at /home/hythm/.rakubrew/versions/moar-HEAD-HEAD-HEAD/install/share/perl6/core/sources/D4356A413F4B0437F7F4404FF5A225216F22EFFA (NativeCall) line 217
Cannot locate native library '/home/hythm/.raku/libresources.so': /home/hythm/.raku/libresources.so: cannot open shared object file: No such file or directory

...
...
in submethod BUILD at /home/hythm/.raku/sources/B15919F9457782C67E2B931F9411A81839F73152 (Term::termios) line 168`
```

Adding back `libraries/myhelper` to meta file resources fixes the issue for me.

**Comment by krunen** [comment]
I'm having trouble getting this to work with fez. I'm looking for other fez modules with a c library, to see if I can copy how they did it.

**Comment by krunen** [comment]
I redid all the LibraryMake stuff based on its latest doc. Tests in Terminal::LineEditor seems to work now.

**Comment by krunen** [comment]
Hmm, zef install gives an error

**Comment by krunen** [comment]
I changed from LibraryMake and Build.rakumod, which does not seem to work nicely with zef, to Distribution::Builder::MakeFromJSON. Building from zef seems to work correctly now.

**Comment by hythm7** [comment]
This looks good except for the `.absolute` call on [this line](https://github.com/krunen/term-termios/blob/master/lib/Term/termios.rakumod#L148) `.absolute` is like `.Str`, it will hardcode the lib path to that location( eg. `/home/user1/.raku/resources/libfoo.so`). This will  work fine if installed in the local system, but if one were to package the distribution and move it to another system ( that have a different  repo path eg. `/home/user2/.raku/`), it will look for the lib in the hardcoded (`/home/user1/.raku/resources/libfoo.so`) path and it will not be able to find it.

Changing said line to `my constant $library = %?RESOURCES<libraries/myhelper>` will make sure the distribution will work when packaged and distributed to other systems as well.

niner's comments [here](https://github.com/rakudo/rakudo/issues/4818#issuecomment-1071136485) and [here](https://github.com/Raku/problem-solving/issues/309#issuecomment-1069619522) explain the issue better.

**Comment by krunen** [comment]
I released 0.2.7 without the .absolute.

**Comment by krunen** [comment]
Will Colleda opened an issue that Distribution::Builder::MakeFromJSON does not compile the helper library on an M2 mac, so there are still problems with this.

**Comment by hythm7** [comment]
Just tested, v0.2.7  works fine for me on Linux, The failure on M2 mac is a different issue, I think.
