### ISSUE TITLE
Incorrect default values of constants

### ISSUE THREAD

**Issue by kjpye** [krunen/term-termios#25]
As I understand the code, the variables `%ilocal`, `%olocal`, `%clocal` and `%llocal` contain default values which are overwritten with system-specific values when an object is created.

Unfortunately most of the default values are wrong. They should all be octal rather than decimal. For example, the default value for `%iflags<IXON>` should be `0o2000` rather than the decimal value `2000`.

**Comment by krunen** [comment]
At some point I swear these were octals! I have changed them now, thanks.
